### ISSUE TITLE
Fingerprint matching

### ISSUE THREAD

**Issue by nguThapelo** [michaseyi/digitalpersona-fingerprint-setup#1]
How do i connect the core to my digitalpersona for fingerprint verification/ identification ? I connected a digital persona do my app and i can get the base64 image to my database, although i am having issues with verifying/ matching the fingerprints

**Comment by javico-dev11** [comment]
Hello, good evening, I have implemented your example and it works perfectly, but only on Localhost, maybe I need something additional to make it work on a domain?

**Comment by javico-dev11** [comment]
@nguThapelo Does it work on a domain (cloud), or have you only tested on localhost?

**Comment by nguThapelo** [comment]
It works on both. local and prod (domain)/ cloud.
